// Generated by Wrangler on Wed May 29 2024 23:03:03 GMT-0230 (Newfoundland Daylight Time)
// by running `wrangler types`

interface Env {
	KV_DEVELOPMENT: KVNamespace;
	KV_PRODUCTION: KVNamespace;
	API_KEY: "xyz789";
	DB_PRODUCTION: D1Database;
	DB_DEVELOPMENT: D1Database;
}
