// Generated by Wrangler on Thu May 23 2024 02:11:56 GMT-0230 (Newfoundland Daylight Time)
// by running `wrangler types`

interface Env {
	KV_DEVELOPMENT: KVNamespace;
	KV_PRODUCTION: KVNamespace;
	API_KEY: "xyz789";
	DB_PRODUCTION: D1Database;
	DB_DEVELOPMENT: D1Database;
}
